language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
script:
  - ./mvnw test
after_script:
branches:
  only:
    - master
